# Meta Data for SEO

## Homepage
title = "Csmart "
titleSeparator = "-"
titleAddition = "Documentation"
description = "Csmart is a cloud based E2E subscriber management and billing solution for enterprises, enabling monetizing the business offerings in a quick time and with no upfront investments."

## Open Graph + Twitter Cards
images = ["csmart-screen.png"]
twitterSite = "Covalensedigi"
twitterCreator = "Covalensedigi"
facebookAuthor = "covalensedigital"
facebookPublisher = "covalensedigital"
ogLocale = "en_US"

## JSON-LD
schemaType = "Organization"
schemaLogo = "cSMART-logo.png"
schemaTwitter = "https://twitter.com/Covalensedigi"
schemaLinkedIn = "https://www.linkedin.com/company/covalensedigital/"
##schemaGitHub = "https://github.com/h-enk"
schemaSection = "documentation"

## Sitelinks Search Box
siteLinksSearchBox = false

## Chrome Browser
themeColor = "#fff"

# Images
quality = 85
bgColor = "#fff"
landscapePhotoWidths = [900, 800, 700, 600, 500]
portraitPhotoWidths = [800, 700, 600, 500]
lqipWidth = "20x"

# Footer
footer = "Powered by <a href=\"https://www.netlify.com/\">Netlify</a>, <a href=\"https://gohugo.io/\">Hugo</a>, and <a href=\"https://www.ukthapa.com/\">ukthapa.com</a>"

# Alert
alert = true
alertText = "Like Doks? <a class=\"alert-link\" href=\"https://github.com/h-enk/doks/stargazers\">Star on GitHub</a>. Thanks!</a>"

# Edit Page
docsRepo = "https://github.com/ukthapa/doc-poc.git"
editPage = false

[options]
  lazySizes = true
  clipBoard = true
  instantPage = true
  flexSearch = true
  darkMode = false
  bootStrapJs = true
  breadCrumb = false
  highLight = true
  kaTex = false
  collapsibleSidebar = true
